[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light" 
primaryColor = "#377dde"  
backgroundColor = "#FFFFFF"  
secondaryBackgroundColor = "#6ca8d4"  
textColor = "#000000"  
font = "sans serif"  